server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alesanderlg/config-server-store
          #username: root
          #passphrase: 123456
          search-paths:
            - '*service'